{{- if .Values.security.externalSecrets.enabled }}
{{- if .Values.security.externalSecrets.secretStore.name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nkudo.fullname" . }}-security
  labels:
    {{- include "nkudo.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.security.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.security.externalSecrets.secretStore.kind }}
    name: {{ .Values.security.externalSecrets.secretStore.name }}
  target:
    name: {{ include "nkudo.securitySecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: admin-key
      remoteRef:
        key: nkudo-admin-key
    - secretKey: jwt-secret
      remoteRef:
        key: nkudo-jwt-secret
---
{{- if .Values.database.external.existingSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nkudo.fullname" . }}-db-credentials
  labels:
    {{- include "nkudo.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.security.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.security.externalSecrets.secretStore.kind }}
    name: {{ .Values.security.externalSecrets.secretStore.name }}
  target:
    name: {{ .Values.database.external.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.external.existingSecretPasswordKey }}
      remoteRef:
        key: nkudo-db-password
{{- end }}
{{- end }}
{{- end }}
