{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "nkudo.fullname" . }}
  labels:
    {{- include "nkudo.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nkudo.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updateMode | quote }}
  {{- with .Values.verticalPodAutoscaler.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
      - containerName: nkudo
        {{- with .minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .controlledResources }}
        controlledResources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- end }}
{{- end }}
